// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: state.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of UEFI firmware log.
type LogType int32

const (
	LogType_LOG_TYPE_UNDEFINED LogType = 0
	// The log used by EFI_TCG2_PROTOCOL and defined in the TCG PC Client
	// Platform Firmware Profile Specification
	LogType_LOG_TYPE_TCG2 LogType = 1
	// The log used by EFI_CC_MEASUREMENT_PROTOCOL and defined in the UEFI spec:
	// https://uefi.org/specs/UEFI/2.10/38_Confidential_Computing.html.
	LogType_LOG_TYPE_CC LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_TYPE_UNDEFINED",
		1: "LOG_TYPE_TCG2",
		2: "LOG_TYPE_CC",
	}
	LogType_value = map[string]int32{
		"LOG_TYPE_UNDEFINED": 0,
		"LOG_TYPE_TCG2":      1,
		"LOG_TYPE_CC":        2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

// Type of hardware technology used to protect this instance
type GCEConfidentialTechnology int32

const (
	GCEConfidentialTechnology_NONE        GCEConfidentialTechnology = 0
	GCEConfidentialTechnology_AMD_SEV     GCEConfidentialTechnology = 1
	GCEConfidentialTechnology_AMD_SEV_ES  GCEConfidentialTechnology = 2
	GCEConfidentialTechnology_INTEL_TDX   GCEConfidentialTechnology = 3
	GCEConfidentialTechnology_AMD_SEV_SNP GCEConfidentialTechnology = 4
)

// Enum value maps for GCEConfidentialTechnology.
var (
	GCEConfidentialTechnology_name = map[int32]string{
		0: "NONE",
		1: "AMD_SEV",
		2: "AMD_SEV_ES",
		3: "INTEL_TDX",
		4: "AMD_SEV_SNP",
	}
	GCEConfidentialTechnology_value = map[string]int32{
		"NONE":        0,
		"AMD_SEV":     1,
		"AMD_SEV_ES":  2,
		"INTEL_TDX":   3,
		"AMD_SEV_SNP": 4,
	}
)

func (x GCEConfidentialTechnology) Enum() *GCEConfidentialTechnology {
	p := new(GCEConfidentialTechnology)
	*p = x
	return p
}

func (x GCEConfidentialTechnology) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GCEConfidentialTechnology) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[1].Descriptor()
}

func (GCEConfidentialTechnology) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[1]
}

func (x GCEConfidentialTechnology) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GCEConfidentialTechnology.Descriptor instead.
func (GCEConfidentialTechnology) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

// Common, publicly-listed certificates by different vendors.
type WellKnownCertificate int32

const (
	WellKnownCertificate_UNKNOWN WellKnownCertificate = 0
	// Microsoft certs:
	// https://go.microsoft.com/fwlink/p/?linkid=321192
	WellKnownCertificate_MS_WINDOWS_PROD_PCA_2011 WellKnownCertificate = 1
	// https://go.microsoft.com/fwlink/p/?linkid=321194
	WellKnownCertificate_MS_THIRD_PARTY_UEFI_CA_2011 WellKnownCertificate = 2
	// https://go.microsoft.com/fwlink/p/?linkid=321185
	WellKnownCertificate_MS_THIRD_PARTY_KEK_CA_2011 WellKnownCertificate = 3
	// GCE certs:
	WellKnownCertificate_GCE_DEFAULT_PK WellKnownCertificate = 4
)

// Enum value maps for WellKnownCertificate.
var (
	WellKnownCertificate_name = map[int32]string{
		0: "UNKNOWN",
		1: "MS_WINDOWS_PROD_PCA_2011",
		2: "MS_THIRD_PARTY_UEFI_CA_2011",
		3: "MS_THIRD_PARTY_KEK_CA_2011",
		4: "GCE_DEFAULT_PK",
	}
	WellKnownCertificate_value = map[string]int32{
		"UNKNOWN":                     0,
		"MS_WINDOWS_PROD_PCA_2011":    1,
		"MS_THIRD_PARTY_UEFI_CA_2011": 2,
		"MS_THIRD_PARTY_KEK_CA_2011":  3,
		"GCE_DEFAULT_PK":              4,
	}
)

func (x WellKnownCertificate) Enum() *WellKnownCertificate {
	p := new(WellKnownCertificate)
	*p = x
	return p
}

func (x WellKnownCertificate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WellKnownCertificate) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[2].Descriptor()
}

func (WellKnownCertificate) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[2]
}

func (x WellKnownCertificate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WellKnownCertificate.Descriptor instead.
func (WellKnownCertificate) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

// Enum values come from the TCG Algorithm Registry - v1.27 - Table 3.
type HashAlgo int32

const (
	HashAlgo_HASH_INVALID HashAlgo = 0
	HashAlgo_SHA1         HashAlgo = 4
	HashAlgo_SHA256       HashAlgo = 11
	HashAlgo_SHA384       HashAlgo = 12
	HashAlgo_SHA512       HashAlgo = 13
)

// Enum value maps for HashAlgo.
var (
	HashAlgo_name = map[int32]string{
		0:  "HASH_INVALID",
		4:  "SHA1",
		11: "SHA256",
		12: "SHA384",
		13: "SHA512",
	}
	HashAlgo_value = map[string]int32{
		"HASH_INVALID": 0,
		"SHA1":         4,
		"SHA256":       11,
		"SHA384":       12,
		"SHA512":       13,
	}
)

func (x HashAlgo) Enum() *HashAlgo {
	p := new(HashAlgo)
	*p = x
	return p
}

func (x HashAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[3].Descriptor()
}

func (HashAlgo) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[3]
}

func (x HashAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgo.Descriptor instead.
func (HashAlgo) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

// Information uniquely identifying a GCE instance. Can be used to create an
// instance URL, which can then be used with GCE APIs. Formatted like:
//
//	https://www.googleapis.com/compute/v1/projects/{project_id}/zones/{zone}/instances/{instance_name}
type GCEInstanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectNumber uint64                 `protobuf:"varint,3,opt,name=project_number,json=projectNumber,proto3" json:"project_number,omitempty"`
	InstanceName  string                 `protobuf:"bytes,4,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	InstanceId    uint64                 `protobuf:"varint,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCEInstanceInfo) Reset() {
	*x = GCEInstanceInfo{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCEInstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCEInstanceInfo) ProtoMessage() {}

func (x *GCEInstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCEInstanceInfo.ProtoReflect.Descriptor instead.
func (*GCEInstanceInfo) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *GCEInstanceInfo) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *GCEInstanceInfo) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GCEInstanceInfo) GetProjectNumber() uint64 {
	if x != nil {
		return x.ProjectNumber
	}
	return 0
}

func (x *GCEInstanceInfo) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *GCEInstanceInfo) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

// The platform/firmware state for this instance
type PlatformState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Firmware:
	//
	//	*PlatformState_ScrtmVersionId
	//	*PlatformState_GceVersion
	Firmware isPlatformState_Firmware `protobuf_oneof:"firmware"`
	// Set to NONE on non-GCE instances or non-Confidential Shielded GCE instances
	Technology GCEConfidentialTechnology `protobuf:"varint,3,opt,name=technology,proto3,enum=state.GCEConfidentialTechnology" json:"technology,omitempty"`
	// Only set for GCE instances.
	// Included for backcompat. go-eventlog should NOT set this field.
	InstanceInfo  *GCEInstanceInfo `protobuf:"bytes,4,opt,name=instance_info,json=instanceInfo,proto3" json:"instance_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformState) Reset() {
	*x = PlatformState{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformState) ProtoMessage() {}

func (x *PlatformState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformState.ProtoReflect.Descriptor instead.
func (*PlatformState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformState) GetFirmware() isPlatformState_Firmware {
	if x != nil {
		return x.Firmware
	}
	return nil
}

func (x *PlatformState) GetScrtmVersionId() []byte {
	if x != nil {
		if x, ok := x.Firmware.(*PlatformState_ScrtmVersionId); ok {
			return x.ScrtmVersionId
		}
	}
	return nil
}

func (x *PlatformState) GetGceVersion() uint32 {
	if x != nil {
		if x, ok := x.Firmware.(*PlatformState_GceVersion); ok {
			return x.GceVersion
		}
	}
	return 0
}

func (x *PlatformState) GetTechnology() GCEConfidentialTechnology {
	if x != nil {
		return x.Technology
	}
	return GCEConfidentialTechnology_NONE
}

func (x *PlatformState) GetInstanceInfo() *GCEInstanceInfo {
	if x != nil {
		return x.InstanceInfo
	}
	return nil
}

type isPlatformState_Firmware interface {
	isPlatformState_Firmware()
}

type PlatformState_ScrtmVersionId struct {
	// Raw S-CRTM version identifier (EV_S_CRTM_VERSION)
	ScrtmVersionId []byte `protobuf:"bytes,1,opt,name=scrtm_version_id,json=scrtmVersionId,proto3,oneof"`
}

type PlatformState_GceVersion struct {
	// Virtual GCE firmware version (parsed from S-CRTM version id)
	GceVersion uint32 `protobuf:"varint,2,opt,name=gce_version,json=gceVersion,proto3,oneof"`
}

func (*PlatformState_ScrtmVersionId) isPlatformState_Firmware() {}

func (*PlatformState_GceVersion) isPlatformState_Firmware() {}

type GrubFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The digest of the file (pulled from the raw event digest).
	Digest []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// The event data. This is not measured, so it is untrusted.
	UntrustedFilename []byte `protobuf:"bytes,2,opt,name=untrusted_filename,json=untrustedFilename,proto3" json:"untrusted_filename,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GrubFile) Reset() {
	*x = GrubFile{}
	mi := &file_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrubFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrubFile) ProtoMessage() {}

func (x *GrubFile) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrubFile.ProtoReflect.Descriptor instead.
func (*GrubFile) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *GrubFile) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *GrubFile) GetUntrustedFilename() []byte {
	if x != nil {
		return x.UntrustedFilename
	}
	return nil
}

type GrubState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All GRUB-read and measured files, including grub.cfg.
	Files []*GrubFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// A list of executed GRUB commands and command lines passed to the kernel
	// and kernel modules.
	Commands      []string `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrubState) Reset() {
	*x = GrubState{}
	mi := &file_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrubState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrubState) ProtoMessage() {}

func (x *GrubState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrubState.ProtoReflect.Descriptor instead.
func (*GrubState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

func (x *GrubState) GetFiles() []*GrubFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GrubState) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

// The state of the Linux kernel.
// At the moment, parsing LinuxKernelState relies on parsing the GrubState.
// To do so, use ExtractOpts{Loader: GRUB} when calling ParseMachineState.
type LinuxKernelState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kernel command line.
	CommandLine   string `protobuf:"bytes,1,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinuxKernelState) Reset() {
	*x = LinuxKernelState{}
	mi := &file_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinuxKernelState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinuxKernelState) ProtoMessage() {}

func (x *LinuxKernelState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinuxKernelState.ProtoReflect.Descriptor instead.
func (*LinuxKernelState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{4}
}

func (x *LinuxKernelState) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

// A parsed event from the source firmware event log. This can be from either
// the firmware TPM event log, the Confidential Computing event log, or any
// other TCG-like event log used by firmware to record its measurements.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The register this event was extended into. Can be PCR, RTMR, etc.
	// Named pcr_index for backcompat reasons.
	PcrIndex uint32 `protobuf:"varint,1,opt,name=pcr_index,json=pcrIndex,proto3" json:"pcr_index,omitempty"`
	// The type of this event. Note that this value is not verified, so it should
	// only be used as a hint during event parsing.
	UntrustedType uint32 `protobuf:"varint,2,opt,name=untrusted_type,json=untrustedType,proto3" json:"untrusted_type,omitempty"`
	// The raw data associated to this event. The meaning of this data is
	// specific to the type of the event.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// The event digest actually extended into the TPM. This is often the hash of
	// the data field, but in some cases it may have a type-specific calculation.
	Digest []byte `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	// This is true if hash(data) == digest.
	DigestVerified bool `protobuf:"varint,5,opt,name=digest_verified,json=digestVerified,proto3" json:"digest_verified,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetPcrIndex() uint32 {
	if x != nil {
		return x.PcrIndex
	}
	return 0
}

func (x *Event) GetUntrustedType() uint32 {
	if x != nil {
		return x.UntrustedType
	}
	return 0
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *Event) GetDigestVerified() bool {
	if x != nil {
		return x.DigestVerified
	}
	return false
}

type Certificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The representation of the certificate. If the certificate matches a
	// well-known certificate above, representation should contain the value in
	// the enum. Otherwise, it will contain the raw DER.
	//
	// Types that are valid to be assigned to Representation:
	//
	//	*Certificate_Der
	//	*Certificate_WellKnown
	Representation isCertificate_Representation `protobuf_oneof:"representation"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{6}
}

func (x *Certificate) GetRepresentation() isCertificate_Representation {
	if x != nil {
		return x.Representation
	}
	return nil
}

func (x *Certificate) GetDer() []byte {
	if x != nil {
		if x, ok := x.Representation.(*Certificate_Der); ok {
			return x.Der
		}
	}
	return nil
}

func (x *Certificate) GetWellKnown() WellKnownCertificate {
	if x != nil {
		if x, ok := x.Representation.(*Certificate_WellKnown); ok {
			return x.WellKnown
		}
	}
	return WellKnownCertificate_UNKNOWN
}

type isCertificate_Representation interface {
	isCertificate_Representation()
}

type Certificate_Der struct {
	// DER representation of the certificate.
	Der []byte `protobuf:"bytes,1,opt,name=der,proto3,oneof"`
}

type Certificate_WellKnown struct {
	WellKnown WellKnownCertificate `protobuf:"varint,2,opt,name=well_known,json=wellKnown,proto3,enum=state.WellKnownCertificate,oneof"`
}

func (*Certificate_Der) isCertificate_Representation() {}

func (*Certificate_WellKnown) isCertificate_Representation() {}

// A Secure Boot database containing lists of hashes and certificates,
// as defined by section 32.4.1 Signature Database in the UEFI spec.
type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certs         []*Certificate         `protobuf:"bytes,1,rep,name=certs,proto3" json:"certs,omitempty"`
	Hashes        [][]byte               `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{7}
}

func (x *Database) GetCerts() []*Certificate {
	if x != nil {
		return x.Certs
	}
	return nil
}

func (x *Database) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// The Secure Boot state for this instance.
type SecureBootState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether Secure Boot is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The Secure Boot signature (allowed) database.
	Db *Database `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
	// The Secure Boot revoked signature (forbidden) database.
	Dbx *Database `protobuf:"bytes,3,opt,name=dbx,proto3" json:"dbx,omitempty"`
	// Authority events post-separator. Pre-separator authorities
	// are currently not supported.
	Authority *Database `protobuf:"bytes,4,opt,name=authority,proto3" json:"authority,omitempty"`
	// The Secure Boot Platform key, used to sign key exchange keys.
	Pk *Database `protobuf:"bytes,5,opt,name=pk,proto3" json:"pk,omitempty"`
	// The Secure Boot Key Exchange Keys, used to sign db and dbx updates.
	Kek           *Database `protobuf:"bytes,6,opt,name=kek,proto3" json:"kek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureBootState) Reset() {
	*x = SecureBootState{}
	mi := &file_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureBootState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureBootState) ProtoMessage() {}

func (x *SecureBootState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureBootState.ProtoReflect.Descriptor instead.
func (*SecureBootState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{8}
}

func (x *SecureBootState) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SecureBootState) GetDb() *Database {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *SecureBootState) GetDbx() *Database {
	if x != nil {
		return x.Dbx
	}
	return nil
}

func (x *SecureBootState) GetAuthority() *Database {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *SecureBootState) GetPk() *Database {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *SecureBootState) GetKek() *Database {
	if x != nil {
		return x.Kek
	}
	return nil
}

type EfiApp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The PE/COFF digest of the EFI application (pulled from the raw event digest).
	// This can also represent digest of the EFI boot/runtime service drivers.
	Digest        []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EfiApp) Reset() {
	*x = EfiApp{}
	mi := &file_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EfiApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EfiApp) ProtoMessage() {}

func (x *EfiApp) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EfiApp.ProtoReflect.Descriptor instead.
func (*EfiApp) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{9}
}

func (x *EfiApp) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

// The verified state of EFI Drivers and Applications. Policy usage on this machine state
// should check the entire set of EFI App digests matches, not a subset.
type EfiState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UEFI's OS Loader code is required to measure attempts to load and execute
	// UEFI applications.
	// UEFI applications are typically bootloaders such as shim and GRUB.
	// These run and are measured using the UEFI LoadImage() service.
	Apps []*EfiApp `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	// The EFI drivers,
	// obtained from https://trustedcomputinggroup.org/wp-content/uploads/TCG_EFI_Platform_1_22_Final_-v15.pdf#page=22.
	// The EFI Boot Services Drivers from adapter or loaded bydriver in adapter.
	BootServicesDrivers []*EfiApp `protobuf:"bytes,2,rep,name=boot_services_drivers,json=bootServicesDrivers,proto3" json:"boot_services_drivers,omitempty"`
	// The EFI Runtime Drivers from adapter or loaded bydriver in adapter.
	RuntimeServicesDrivers []*EfiApp `protobuf:"bytes,3,rep,name=runtime_services_drivers,json=runtimeServicesDrivers,proto3" json:"runtime_services_drivers,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EfiState) Reset() {
	*x = EfiState{}
	mi := &file_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EfiState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EfiState) ProtoMessage() {}

func (x *EfiState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EfiState.ProtoReflect.Descriptor instead.
func (*EfiState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{10}
}

func (x *EfiState) GetApps() []*EfiApp {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *EfiState) GetBootServicesDrivers() []*EfiApp {
	if x != nil {
		return x.BootServicesDrivers
	}
	return nil
}

func (x *EfiState) GetRuntimeServicesDrivers() []*EfiApp {
	if x != nil {
		return x.RuntimeServicesDrivers
	}
	return nil
}

// The verified state of a booted machine, obtained from a UEFI event log.
// The state is extracted from either EFI_TCG2_PROTOCOL or
// EFI_CC_MEASUREMENT_PROTOCOL. Both of these follow the TCG-defined format
// in https://trustedcomputinggroup.org/resource/tcg-efi-protocol-specification/
// The TCG2-related (TPM) logs are structured using TCG_PCR_EVENT (SHA1 format)
// or TCG_PCR_EVENT2 (Crypto Agile format).
// The CC logs are structured using CC_EVENT.
type FirmwareLogState struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Platform   *PlatformState         `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	SecureBoot *SecureBootState       `protobuf:"bytes,2,opt,name=secure_boot,json=secureBoot,proto3" json:"secure_boot,omitempty"`
	// The complete parsed Firmware Event Log, including those events used to
	// create this MachineState.
	RawEvents []*Event `protobuf:"bytes,3,rep,name=raw_events,json=rawEvents,proto3" json:"raw_events,omitempty"`
	// The hash algorithm used to calculate event digests to verify a log entry.
	Hash          HashAlgo          `protobuf:"varint,4,opt,name=hash,proto3,enum=state.HashAlgo" json:"hash,omitempty"`
	Grub          *GrubState        `protobuf:"bytes,5,opt,name=grub,proto3" json:"grub,omitempty"`
	LinuxKernel   *LinuxKernelState `protobuf:"bytes,6,opt,name=linux_kernel,json=linuxKernel,proto3" json:"linux_kernel,omitempty"`
	Efi           *EfiState         `protobuf:"bytes,8,opt,name=efi,proto3" json:"efi,omitempty"`
	LogType       LogType           `protobuf:"varint,9,opt,name=log_type,json=logType,proto3,enum=state.LogType" json:"log_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareLogState) Reset() {
	*x = FirmwareLogState{}
	mi := &file_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareLogState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareLogState) ProtoMessage() {}

func (x *FirmwareLogState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareLogState.ProtoReflect.Descriptor instead.
func (*FirmwareLogState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{11}
}

func (x *FirmwareLogState) GetPlatform() *PlatformState {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *FirmwareLogState) GetSecureBoot() *SecureBootState {
	if x != nil {
		return x.SecureBoot
	}
	return nil
}

func (x *FirmwareLogState) GetRawEvents() []*Event {
	if x != nil {
		return x.RawEvents
	}
	return nil
}

func (x *FirmwareLogState) GetHash() HashAlgo {
	if x != nil {
		return x.Hash
	}
	return HashAlgo_HASH_INVALID
}

func (x *FirmwareLogState) GetGrub() *GrubState {
	if x != nil {
		return x.Grub
	}
	return nil
}

func (x *FirmwareLogState) GetLinuxKernel() *LinuxKernelState {
	if x != nil {
		return x.LinuxKernel
	}
	return nil
}

func (x *FirmwareLogState) GetEfi() *EfiState {
	if x != nil {
		return x.Efi
	}
	return nil
}

func (x *FirmwareLogState) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_LOG_TYPE_UNDEFINED
}

// The verified state of Google measurements on the machine.
type GMESState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BmcFirmware   string                 `protobuf:"bytes,1,opt,name=bmc_firmware,json=bmcFirmware,proto3" json:"bmc_firmware,omitempty"`
	Bios          string                 `protobuf:"bytes,2,opt,name=bios,proto3" json:"bios,omitempty"`
	HostKernel    string                 `protobuf:"bytes,3,opt,name=host_kernel,json=hostKernel,proto3" json:"host_kernel,omitempty"`
	Mbm           string                 `protobuf:"bytes,4,opt,name=mbm,proto3" json:"mbm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GMESState) Reset() {
	*x = GMESState{}
	mi := &file_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GMESState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMESState) ProtoMessage() {}

func (x *GMESState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMESState.ProtoReflect.Descriptor instead.
func (*GMESState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{12}
}

func (x *GMESState) GetBmcFirmware() string {
	if x != nil {
		return x.BmcFirmware
	}
	return ""
}

func (x *GMESState) GetBios() string {
	if x != nil {
		return x.Bios
	}
	return ""
}

func (x *GMESState) GetHostKernel() string {
	if x != nil {
		return x.HostKernel
	}
	return ""
}

func (x *GMESState) GetMbm() string {
	if x != nil {
		return x.Mbm
	}
	return ""
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\x05state\"\xb1\x01\n" +
	"\x0fGCEInstanceInfo\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12%\n" +
	"\x0eproject_number\x18\x03 \x01(\x04R\rprojectNumber\x12#\n" +
	"\rinstance_name\x18\x04 \x01(\tR\finstanceName\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\x04R\n" +
	"instanceId\"\xe9\x01\n" +
	"\rPlatformState\x12*\n" +
	"\x10scrtm_version_id\x18\x01 \x01(\fH\x00R\x0escrtmVersionId\x12!\n" +
	"\vgce_version\x18\x02 \x01(\rH\x00R\n" +
	"gceVersion\x12@\n" +
	"\n" +
	"technology\x18\x03 \x01(\x0e2 .state.GCEConfidentialTechnologyR\n" +
	"technology\x12;\n" +
	"\rinstance_info\x18\x04 \x01(\v2\x16.state.GCEInstanceInfoR\finstanceInfoB\n" +
	"\n" +
	"\bfirmware\"Q\n" +
	"\bGrubFile\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x12-\n" +
	"\x12untrusted_filename\x18\x02 \x01(\fR\x11untrustedFilename\"N\n" +
	"\tGrubState\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.state.GrubFileR\x05files\x12\x1a\n" +
	"\bcommands\x18\x02 \x03(\tR\bcommands\"5\n" +
	"\x10LinuxKernelState\x12!\n" +
	"\fcommand_line\x18\x01 \x01(\tR\vcommandLine\"\xa0\x01\n" +
	"\x05Event\x12\x1b\n" +
	"\tpcr_index\x18\x01 \x01(\rR\bpcrIndex\x12%\n" +
	"\x0euntrusted_type\x18\x02 \x01(\rR\runtrustedType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\fR\x06digest\x12'\n" +
	"\x0fdigest_verified\x18\x05 \x01(\bR\x0edigestVerified\"q\n" +
	"\vCertificate\x12\x12\n" +
	"\x03der\x18\x01 \x01(\fH\x00R\x03der\x12<\n" +
	"\n" +
	"well_known\x18\x02 \x01(\x0e2\x1b.state.WellKnownCertificateH\x00R\twellKnownB\x10\n" +
	"\x0erepresentation\"L\n" +
	"\bDatabase\x12(\n" +
	"\x05certs\x18\x01 \x03(\v2\x12.state.CertificateR\x05certs\x12\x16\n" +
	"\x06hashes\x18\x02 \x03(\fR\x06hashes\"\xe2\x01\n" +
	"\x0fSecureBootState\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\x02db\x18\x02 \x01(\v2\x0f.state.DatabaseR\x02db\x12!\n" +
	"\x03dbx\x18\x03 \x01(\v2\x0f.state.DatabaseR\x03dbx\x12-\n" +
	"\tauthority\x18\x04 \x01(\v2\x0f.state.DatabaseR\tauthority\x12\x1f\n" +
	"\x02pk\x18\x05 \x01(\v2\x0f.state.DatabaseR\x02pk\x12!\n" +
	"\x03kek\x18\x06 \x01(\v2\x0f.state.DatabaseR\x03kek\" \n" +
	"\x06EfiApp\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\"\xb9\x01\n" +
	"\bEfiState\x12!\n" +
	"\x04apps\x18\x01 \x03(\v2\r.state.EfiAppR\x04apps\x12A\n" +
	"\x15boot_services_drivers\x18\x02 \x03(\v2\r.state.EfiAppR\x13bootServicesDrivers\x12G\n" +
	"\x18runtime_services_drivers\x18\x03 \x03(\v2\r.state.EfiAppR\x16runtimeServicesDrivers\"\x85\x03\n" +
	"\x10FirmwareLogState\x120\n" +
	"\bplatform\x18\x01 \x01(\v2\x14.state.PlatformStateR\bplatform\x127\n" +
	"\vsecure_boot\x18\x02 \x01(\v2\x16.state.SecureBootStateR\n" +
	"secureBoot\x12+\n" +
	"\n" +
	"raw_events\x18\x03 \x03(\v2\f.state.EventR\trawEvents\x12#\n" +
	"\x04hash\x18\x04 \x01(\x0e2\x0f.state.HashAlgoR\x04hash\x12$\n" +
	"\x04grub\x18\x05 \x01(\v2\x10.state.GrubStateR\x04grub\x12:\n" +
	"\flinux_kernel\x18\x06 \x01(\v2\x17.state.LinuxKernelStateR\vlinuxKernel\x12!\n" +
	"\x03efi\x18\b \x01(\v2\x0f.state.EfiStateR\x03efi\x12)\n" +
	"\blog_type\x18\t \x01(\x0e2\x0e.state.LogTypeR\alogTypeJ\x04\b\a\x10\b\"u\n" +
	"\tGMESState\x12!\n" +
	"\fbmc_firmware\x18\x01 \x01(\tR\vbmcFirmware\x12\x12\n" +
	"\x04bios\x18\x02 \x01(\tR\x04bios\x12\x1f\n" +
	"\vhost_kernel\x18\x03 \x01(\tR\n" +
	"hostKernel\x12\x10\n" +
	"\x03mbm\x18\x04 \x01(\tR\x03mbm*E\n" +
	"\aLogType\x12\x16\n" +
	"\x12LOG_TYPE_UNDEFINED\x10\x00\x12\x11\n" +
	"\rLOG_TYPE_TCG2\x10\x01\x12\x0f\n" +
	"\vLOG_TYPE_CC\x10\x02*b\n" +
	"\x19GCEConfidentialTechnology\x12\b\n" +
	"\x04NONE\x10\x00\x12\v\n" +
	"\aAMD_SEV\x10\x01\x12\x0e\n" +
	"\n" +
	"AMD_SEV_ES\x10\x02\x12\r\n" +
	"\tINTEL_TDX\x10\x03\x12\x0f\n" +
	"\vAMD_SEV_SNP\x10\x04*\x96\x01\n" +
	"\x14WellKnownCertificate\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x1c\n" +
	"\x18MS_WINDOWS_PROD_PCA_2011\x10\x01\x12\x1f\n" +
	"\x1bMS_THIRD_PARTY_UEFI_CA_2011\x10\x02\x12\x1e\n" +
	"\x1aMS_THIRD_PARTY_KEK_CA_2011\x10\x03\x12\x12\n" +
	"\x0eGCE_DEFAULT_PK\x10\x04*J\n" +
	"\bHashAlgo\x12\x10\n" +
	"\fHASH_INVALID\x10\x00\x12\b\n" +
	"\x04SHA1\x10\x04\x12\n" +
	"\n" +
	"\x06SHA256\x10\v\x12\n" +
	"\n" +
	"\x06SHA384\x10\f\x12\n" +
	"\n" +
	"\x06SHA512\x10\rB+Z)github.com/google/go-eventlog/proto/stateb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_state_proto_goTypes = []any{
	(LogType)(0),                   // 0: state.LogType
	(GCEConfidentialTechnology)(0), // 1: state.GCEConfidentialTechnology
	(WellKnownCertificate)(0),      // 2: state.WellKnownCertificate
	(HashAlgo)(0),                  // 3: state.HashAlgo
	(*GCEInstanceInfo)(nil),        // 4: state.GCEInstanceInfo
	(*PlatformState)(nil),          // 5: state.PlatformState
	(*GrubFile)(nil),               // 6: state.GrubFile
	(*GrubState)(nil),              // 7: state.GrubState
	(*LinuxKernelState)(nil),       // 8: state.LinuxKernelState
	(*Event)(nil),                  // 9: state.Event
	(*Certificate)(nil),            // 10: state.Certificate
	(*Database)(nil),               // 11: state.Database
	(*SecureBootState)(nil),        // 12: state.SecureBootState
	(*EfiApp)(nil),                 // 13: state.EfiApp
	(*EfiState)(nil),               // 14: state.EfiState
	(*FirmwareLogState)(nil),       // 15: state.FirmwareLogState
	(*GMESState)(nil),              // 16: state.GMESState
}
var file_state_proto_depIdxs = []int32{
	1,  // 0: state.PlatformState.technology:type_name -> state.GCEConfidentialTechnology
	4,  // 1: state.PlatformState.instance_info:type_name -> state.GCEInstanceInfo
	6,  // 2: state.GrubState.files:type_name -> state.GrubFile
	2,  // 3: state.Certificate.well_known:type_name -> state.WellKnownCertificate
	10, // 4: state.Database.certs:type_name -> state.Certificate
	11, // 5: state.SecureBootState.db:type_name -> state.Database
	11, // 6: state.SecureBootState.dbx:type_name -> state.Database
	11, // 7: state.SecureBootState.authority:type_name -> state.Database
	11, // 8: state.SecureBootState.pk:type_name -> state.Database
	11, // 9: state.SecureBootState.kek:type_name -> state.Database
	13, // 10: state.EfiState.apps:type_name -> state.EfiApp
	13, // 11: state.EfiState.boot_services_drivers:type_name -> state.EfiApp
	13, // 12: state.EfiState.runtime_services_drivers:type_name -> state.EfiApp
	5,  // 13: state.FirmwareLogState.platform:type_name -> state.PlatformState
	12, // 14: state.FirmwareLogState.secure_boot:type_name -> state.SecureBootState
	9,  // 15: state.FirmwareLogState.raw_events:type_name -> state.Event
	3,  // 16: state.FirmwareLogState.hash:type_name -> state.HashAlgo
	7,  // 17: state.FirmwareLogState.grub:type_name -> state.GrubState
	8,  // 18: state.FirmwareLogState.linux_kernel:type_name -> state.LinuxKernelState
	14, // 19: state.FirmwareLogState.efi:type_name -> state.EfiState
	0,  // 20: state.FirmwareLogState.log_type:type_name -> state.LogType
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	file_state_proto_msgTypes[1].OneofWrappers = []any{
		(*PlatformState_ScrtmVersionId)(nil),
		(*PlatformState_GceVersion)(nil),
	}
	file_state_proto_msgTypes[6].OneofWrappers = []any{
		(*Certificate_Der)(nil),
		(*Certificate_WellKnown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		EnumInfos:         file_state_proto_enumTypes,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
